# Generated by Django 4.0.2 on 2022-04-01 11:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses2', '0008_alter_lessonview_lesson'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='action',
            unique_together={('creater', 'lesson')},
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('creater', 'lesson')},
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('active', models.BooleanField(default=False)),
                ('creater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses2.lesson')),
            ],
            options={
                'abstract': False,
                'unique_together': {('creater', 'lesson')},
            },
        ),
    ]
